// This is a server-side layout
export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

import './globals.css'
import Navbar from "@/components/Navbar"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=''>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
